{% set name = "afscgap" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/afscgap-{{ version }}.tar.gz
  sha256: 8cfb6140bbf567fef538d3410fcb38d375a77b4f22fb0e42b37cecb433a1e55b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - requests >=2.28.2,<2.29.dev0

test:
  imports:
    - afscgap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pyafscgap.org/
  summary: Tools for interacting with the public bottom trawl surveys data from the NOAA AFSC GAP.
  dev_url: https://github.com/SchmidtDSE/afscgap
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
