{% set name = "afscgap" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/afscgap-{{ version }}.tar.gz
  sha256: 6284ddcbb76acd167e850684aa070c6a6d4b0ac267c609d78242e7e847e5b3ec

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - fastavro >=1.9.7,<1.10.dev0
    - python >={{ python_min }}
    - requests >=2.32.3,<2.33.dev0

test:
  imports:
    - afscgap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyafscgap.org/
  summary: Tools for interacting with the public bottom trawl surveys data from the NOAA AFSC GAP.
  dev_url: https://github.com/SchmidtDSE/afscgap
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
