{% set name = "afscgap" %}
{% set version = "1.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/afscgap-{{ version }}.tar.gz
  sha256: 79b344a29d7f2baaca2b64cac5d8450ca3ee5f444454ce7eb7fe990a46c631b1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - requests >=2.28.2,<2.29.dev0

test:
  imports:
    - afscgap
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pyafscgap.org/
  summary: Tools for interacting with the public bottom trawl surveys data from the NOAA AFSC GAP.
  dev_url: https://github.com/SchmidtDSE/afscgap
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
