{% set name = "afscgap" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/afscgap-{{ version }}.tar.gz
  sha256: f5a9b3af53a7474c7665cc89a8e4f8c703409276c2a69042df45f55e552df216

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling
    - pip
  run:
    - python >=3.7
    - requests >=2.28.2,<2.29.dev0

test:
  imports:
    - afscgap
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pyafscgap.org/
  summary: Tools for interacting with the public bottom trawl surveys data from the NOAA AFSC GAP.
  dev_url: https://github.com/SchmidtDSE/afscgap
  license: BSD-3-Clause
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - ocefpaf
